spring.application.name=testexe
server.port=8080
# SQLite
spring.datasource.url=jdbc:sqlite:data.db?journal_mode=WAL&busy_timeout=5000
spring.datasource.driver-class-name=org.sqlite.JDBC
# Hikari (🔥 IMPORTANTISSIMO)
spring.datasource.hikari.maximum-pool-size=1
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=10000
spring.jackson.mapper.use-annotations=true
spring.aop.proxy-target-class=false
# JPA
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false