name: Build & Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - run: cd BE && mvn clean package -DskipTests
      - run: cd FE && npm install
      - run: cd FE && npx tsc -p tsconfig.electron.json
      - run: cd FE && npm run electron:build

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            FE/release/*.exe
            FE/release/latest.yml
            FE/release/*.blockmap
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
